### ISSUE TITLE
make from stdin uses untagged ascii stream

### ISSUE THREAD

**Issue by ZOSOpenTools** [ZOSOpenTools/makeport#3]
Give the Makefile:
```
all:
	echo "Hello"
```
run the command:
```
sed -e 's/Hello/Jello/g' Makefile      | make -f - all 
```
and it will fail with:
```
/tmp/GmehfDxQ:1: *** missing separator.  Stop.
```
(the temporary file name will be different).
This is because it is ASCII text but is not tagged as such

**Comment by IgorTodorovskiIBM** [comment]
Should be fixed with https://github.com/ZOSOpenTools/makeport/pull/4
